#!/bin/bash

cd /home/aly/NTI/task_3

if test -f newEnv_variable; then
	echo "HELLO=$HOSTNAME" >> /home/aly/.bashrc
	echo "LOCAL=$(whoami)" >> /home/aly/.bashrc

	gnome-terminal

else
	echo "file does not exist"
fi
